openapi: 3.0.0
info:
  title: web map api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/trees/{treeId}':
    parameters:
      - schema:
          type: string
        name: treeId
        in: path
        required: true
    get:
      summary: get tree info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tree'
      operationId: get-trees-treeId
  /trees/featured:
    get:
      summary: get featured tree list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tree'
      operationId: get-trees-featured
      description: this is some good trees bookmarked by admin
  /countries/leader:
    get:
      summary: leader board of country
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/country'
      operationId: get-countries-leader
      description: a board of leader country
  '/planters/{planterId}':
    parameters:
      - schema:
          type: string
        name: planterId
        in: path
        required: true
    get:
      summary: get planter info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/planter'
      operationId: get-planters-planterId
  '/organizations/{orgId}':
    parameters:
      - schema:
          type: string
        name: orgId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organization'
      operationId: get-organizations-orgId
components:
  schemas:
    tree:
      description: ''
      type: object
      x-examples:
        example-tree:
          id: 933042
          photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
          verified: true
          token_id: d4bb294b-8c75-4e0f-af43-1cd9a35e1033
          impact_manager_id: 8599f832-145e-11ec-82a8-0242ac130003
          impact_producer_id: a0b6b70e-145e-11ec-82a8-0242ac130003
          created_at: '5/18/2021, 5:14:48 PM'
          lat: -4.881696978000001
          lon: 38.37997515399998
          species: Markhamia lutea
          planter_id: 5
          value:
            id: 933042
            photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
            verified: true
            token_id: d4bb294b-8c75-4e0f-af43-1cd9a35e1033
            impact_manager_id: 8599f832-145e-11ec-82a8-0242ac130003
            impact_producer_id: a0b6b70e-145e-11ec-82a8-0242ac130003
            created_at: '5/18/2021, 5:14:48 PM'
            lat: -4.881696978000001
            lon: 38.37997515399998
            species: Markhamia lutea
            planter_id: 5
            organization_id: 1
      title: ''
      properties:
        id:
          type: number
        photo_url:
          type: string
          minLength: 1
        verified:
          type: boolean
        token_id:
          type: string
          minLength: 1
        impact_manager_id:
          type: string
          minLength: 1
        impact_producer_id:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        lat:
          type: number
        lon:
          type: number
        species:
          type: string
          minLength: 1
        planter_id:
          type: number
        organization_id:
          type: number
      required:
        - id
        - photo_url
        - verified
        - token_id
        - impact_manager_id
        - impact_producer_id
        - created_at
        - lat
        - lon
        - species
        - planter_id
    country:
      description: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
        planted:
          type: number
        id:
          type: string
          minLength: 1
        continent:
          type: string
          minLength: 1
      required:
        - name
        - planted
        - id
        - continent
      x-examples:
        example-country:
          name: Tanzania
          planted: 100000
          id: ef883620-15d8-11ec-9c2b-0242ac130003
          continent: Africa
          value:
            name: Tanzania
            planted: 100000
            id: ef883620-15d8-11ec-9c2b-0242ac130003
            continent: Africa
    planter:
      description: ''
      type: object
      x-examples:
        example-planter:
          id: 5
          photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
          name: Issa H
          tree_planted: 981
          tree_reject_rate: 0.01
          about: 'Greenway is a Youth-Driven Environmental Protection Organization providing alternative solutions to single-use plastic and planting carbon-sucking trees for socio-economic development and reducing climate crisis. Our social work includes reforestation, landscape restoration, climate education, awareness campaign, conducting research, outreach activities, and collaborating with key stakeholders to implement sustainable solutions.'
          mission: 'To combat climate change, desertification, land degradation, carbon emission by inspiring healthier communities affected by severe climate disorder and modestly reducing pollution by 2050.'
      properties:
        id:
          type: number
        photo_url:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        tree_planted:
          type: number
        tree_reject_rate:
          type: number
        about:
          type: string
        location:
          type: string
      required:
        - id
        - photo_url
        - name
    organization:
      description: ''
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        photo_url:
          type: string
          minLength: 1
        area:
          type: string
          minLength: 1
        country:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        about:
          type: string
          minLength: 1
        mission:
          type: string
          minLength: 1
      required:
        - id
        - name
        - photo_url
        - area
        - country
        - created_at
        - about
        - mission
      x-examples:
        example-org:
          id: 1
          name: 180Earth
          photo_url: 'https://180.earth/wp-content/uploads/2020/01/Asset-1.png'
          area: Shirimatunda
          country: Tanzania
          created_at: 'November 11, 2019'
          about: 'Greenway is a Youth-Driven Environmental Protection Organization providing alternative solutions to single-use plastic and planting carbon-sucking trees for socio-economic development and reducing climate crisis. Our social work includes reforestation, landscape restoration, climate education, awareness campaign, conducting research, outreach activities, and collaborating with key stakeholders to implement sustainable solutions.'
          mission: 'To combat climate change, desertification, land degradation, carbon emission by inspiring healthier communities affected by severe climate disorder and modestly reducing pollution by 2050.'
          value:
            id: 1
            name: 180Earth
            photo_url: 'https://180.earth/wp-content/uploads/2020/01/Asset-1.png'
            area: Shirimatunda
            country: Tanzania
            created_at: 'November 11, 2019'
            about: 'Greenway is a Youth-Driven Environmental Protection Organization providing alternative solutions to single-use plastic and planting carbon-sucking trees for socio-economic development and reducing climate crisis. Our social work includes reforestation, landscape restoration, climate education, awareness campaign, conducting research, outreach activities, and collaborating with key stakeholders to implement sustainable solutions.'
            mission: 'To combat climate change, desertification, land degradation, carbon emission by inspiring healthier communities affected by severe climate disorder and modestly reducing pollution by 2050.'
