apiVersion: v1
kind: Service
metadata:
  name: treetracker-web-map-client-svc-next
  labels:
    app: treetracker-web-map-client-next
    name: treetracker-web-map-client-svc-next
  namespace: webmap
spec:
  selector:
    app: treetracker-web-map-client-next
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
