apiVersion: v1
kind: Service
metadata:
  name: treetracker-web-map-client-svc-alpha
  labels:
    app: treetracker-web-map-client-alpha
    name: treetracker-web-map-client-svc-alpha
  namespace: webmap
spec:
  selector:
    app: treetracker-web-map-client-alpha
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
