const typographyData = [
  {
    typography: 'h1. Heading',
    size: '48px (32px)',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    lineHeight: '63px (32px)',
    letterSpacing: '-',
  },
  {
    typography: 'h2. Heading',
    size: '36px (24px)',
    fontFamily: 'Montserrat',
    fontWeight: '700',
    lineHeight: '44px (29.26px)',
    letterSpacing: '-',
  },
  {
    typography: 'h3. Heading',
    size: '32px (20px)',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    lineHeight: '39px (24px)',
    letterSpacing: '-',
  },
  {
    typography: 'h4. Heading',
    size: '28px (20px)',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    lineHeight: '33.6px (24px)',
    letterSpacing: '0',
  },
  {
    typography: 'h5. Heading',
    size: '20px (16px)',
    fontFamily: 'Montserrat',
    fontWeight: '700',
    lineHeight: '24px (19.5px)',
    letterSpacing: '0.02em',
  },
  {
    typography: 'h6. Heading',
    size: '16px (16px)',
    fontFamily: 'Lato',
    fontWeight: '700',
    lineHeight: '19px (19px)',
    letterSpacing: '0.02em',
  },
  {
    typography: 'body1',
    size: '16px (12px)',
    fontFamily: 'Lato',
    fontWeight: '400',
    lineHeight: '19.2px (14.4px)',
    letterSpacing: '0.04em',
  },
  {
    typography: 'body2',
    size: '20px (16px)',
    fontFamily: 'Lato',
    fontWeight: '400',
    lineHeight: '28px (23.2px)',
    letterSpacing: '0.04em (0.02em)',
  },
  {
    typography: 'caption',
    size: '12px',
    fontFamily: 'Lato',
    fontWeight: '400',
    lineHeight: '14.4px',
    letterSpacing: '0.04em',
  },
];

export default typographyData;
